[package]
name = "guest_code_for_SpotCheck"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
spotcheck_core={path="../../core/"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

